[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["src"]

[tool.setuptools.package-data]
"*" = ["data/**/*"]

[project]
name = "mccole"
version = "1.3.7"
requires-python = ">=3.12"
authors = [
    {name = "Greg Wilson", email = "gvwilson@third-bit.com"},
]
maintainers = [
    {name = "Greg Wilson", email = "gvwilson@third-bit.com"},
]
description = "A simple static site generator for tutorials"
keywords = ["open source", "static site generator"]
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "beautifulsoup4>=4.14.3",
    "html5validator>=0.4.2",
    "jinja2>=3.1.6",
    "markdown>=3.10",
    "mkdocs>=1.6.1",
    "mkdocstrings[python]>=1.0.0",
    "pygments>=2.19.2",
    "tomli>=2.3.0"
]

[project.optional-dependencies]
dev = [
    "build>=1.3.0",
    "markdown-include>=0.8.1",
    "pytest>=9.0.2",
    "ruff>=0.14.10",
    "twine>=6.2.0"
]

[project.scripts]
mccole = "src:clui.main"
