[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["src"]

[tool.setuptools.package-data]
"*" = ["data/**/*"]

[project]
name = "mccole"
version = "1.3.1"
requires-python = ">=3.12"
authors = [
    {name = "Greg Wilson", email = "gvwilson@third-bit.com"},
]
maintainers = [
    {name = "Greg Wilson", email = "gvwilson@third-bit.com"},
]
description = "A simple static site generator for tutorials"
keywords = ["open source", "static site generator"]
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "beautifulsoup4",
    "html5validator",
    "jinja2",
    "markdown",
    "mkdocs",
    "mkdocstrings[python]",
    "tomli"
]

[project.optional-dependencies]
dev = [
    "build",
    "markdown-include",
    "pytest",
    "ruff",
    "twine"
]

[project.scripts]
mccole = "src:clui.main"
